FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5000

ENV PORT=5000
ENV CLIENT_URL=http://localhost:5173

RUN npm install -g pm2

CMD ["pm2-runtime", "server.js"]
